//ingredients
///export const GET_INGREDIENTS = 'GET_INGREDIENTS';
export const GET_INGREDIENTS_REQUEST = 'GET_INGREDIENTS_REQUEST';
export const GET_INGREDIENTS_SUCCESS = 'GET_INGREDIENTS_SUCCESS';
export const GET_INGREDIENTS_FAILED = 'GET_INGREDIENTS_FAILED';
//constructor 
export const GET_CONSTRUCTOR_INGREDIENT = 'GET_CONSTRUCTOR_INGREDIENT';
export const ADD_CONSTRUCTOR_INGREDIENT = 'ADD_CONSTRUCTOR_INGREDIENT';
export const DELETE_CONSTRUCTOR_INGREDIENT = 'DELETE_CONSTRUCTOR_INGREDIENT';
export const RESET_CONSTRUCTOR = 'RESET_CONSTRUCTOR';
export const SWAP_CONSTRUCTOR_INGREDIENT = 'SWAP_CONSTRUCTOR_INGREDIENT';
//viewedItem
export const SET_VIEW_ITEM = 'SET_VIEW_ITEM';
export const RESET_VIEW_ITEM = 'RESET_VIEW_ITEM';
//order
///export const GET_ORDER_NUMBER = 'GET_ORDER_NUMBER'; 
export const GET_ORDER_NUMBER_REQUEST = 'GET_ORDER_NUMBER_REQUEST';
export const GET_ORDER_NUMBER_SUCCESS = 'GET_ORDER_NUMBER_SUCCESS';
export const GET_ORDER_NUMBER_FAILED = 'GET_ORDER_NUMBER_FAILED';
export const GET_ORDER_REQUEST = 'GET_ORDER_REQUEST';
export const GET_ORDER_SUCCESS = 'GET_ORDER_SUCCESS';
export const GET_ORDER_FAILED = 'GET_ORDER_FAILED';
export const SET_ORDER_ERROR = 'SET_ORDER_ERROR';
//modals
export const OPEN_MODAL_DETAILS = 'OPEN_MODAL_DETAILS';
export const CLOSE_MODAL_DETAILS = 'CLOSE_MODAL_DETAILS';
export const OPEN_MODAL_ORDER = 'OPEN_MODAL_ORDER';
export const CLOSE_MODAL_ORDER = 'CLOSE_MODAL_ORDER';
//sign
export const GET_AUTH_REQUEST = 'GET_AUTH_REQUEST';
export const GET_AUTH_SUCCESS = 'GET_AUTH_SUCCESS';
export const   GET_AUTH_FAILED = 'GET_AUTH_FAILED';
export const   SET_AUTH_ERROR = 'SET_AUTH_ERROR';
export const   GET_REGISTER_REQUEST = 'GET_REGISTER_REQUEST';
export const   GET_REGISTER_SUCCESS = 'GET_REGISTER_SUCCESS';
export const   GET_REGISTER_FAILED = 'GET_REGISTER_FAILED';
export const   SET_REGISTER_ERROR = 'SET_REGISTER_ERROR';
export const   GET_PROFILE_REQUEST = 'GET_PROFILE_REQUEST';
export const   GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const   GET_PROFILE_FAILED = 'GET_PROFILE_FAILED';
export const   SET_PROFILE_ERROR = 'SET_PROFILE_ERROR';
export const   SET_PROFILE_CLEAR = 'SET_PROFILE_CLEAR';